version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - "./backend:/application"
            - "./frontend/dist:/fe"
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${API_PORT-80}:80'
            - '${FE_PORT-8080}:8080'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - "./backend:/application"
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'

    redis:
        image: 'redis:alpine'
        ports:
            - '${REDIS_PORT-6379}:6379'

    node:
        image: 'node:20-buster'
        working_dir: /home/node/app
        command: "npm i && npm run build"
        volumes:
            - "./frontend:/home/node/app"
