name: PHP Unit Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        working_dir: backend/
        php_extensions: intl iconv ctype gd sodium zip
        php_version: "8.3"
    - name: Unit tests
      uses: php-actions/phpunit@v3
      with:
        php_version: "8.3"
        php_extensions: intl iconv ctype gd sodium zip
        version: "9.5.0"
        bootstrap: backend/vendor/autoload.php
        configuration: backend/phpunit.xml.dist
        args: --coverage-text
