name: PHP Unit Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        working_dir: backend/

        
    - name: Unit tests
      uses: php-actions/phpunit@v3
      with:
            bootstrap: backend/vendor/autoload.php
            configuration: test/phpunit.xml
            args: --coverage-text
